# .github/workflows/archive-inactive-repos.yml
name: Archive inactive repos with exceptions

on:
  schedule:
    - cron: '0 0 1 * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  archive:
    runs-on: ubuntu-24.04

    env:
      # Dias sem push para considerar inativo
      THRESHOLD_DAYS: '800'
      # Lista de nomes exatos a pular (vírgula separada)
      EXCLUDE_NAMES: 'Velero-Backup-and-Restore-AKS,Udemy-DevOps-Mao-na-massa,redis-app'
      # Regex para pular nome de repo
      EXCLUDE_PATTERN: 'DevOpsPro, Projetos'

    steps:
      - name: Install GitHub CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y gh

      - name: Authenticate GitHub CLI
        run: |
          echo "${{ secrets.USER_PAT }}" | gh auth login --with-token

      - name: Fetch inactive repos
        id: list
        run: |
          gh api /user/repos --paginate \
            -H "Accept: application/vnd.github+json" \
            -q '.[] 
                | select(
                    ((now - (.pushed_at|fromdateiso8601)) / 86400) > '"${THRESHOLD_DAYS}"' 
                    and .archived==false
                  ) 
                | .name' \
            > all-inactive.txt

          # Remove nomes exatos (exclusão linha a linha)
          if [ -n "${EXCLUDE_NAMES}" ]; then
            IFS=',' read -ra SKIP <<< "${EXCLUDE_NAMES}"
            for repo in "${SKIP[@]}"; do
              grep -vFx "$repo" all-inactive.txt > tmp && mv tmp all-inactive.txt
            done
          fi

          # Remove padrões regex múltiplos
          if [ -n "${EXCLUDE_PATTERN}" ]; then
            # converte "DevOpsPro, Projetos" em "DevOpsPro|Projetos"
            IFS=',' read -ra PATTERNS <<< "${EXCLUDE_PATTERN}"
            REGEX=$(printf '|%s' "${PATTERNS[@]}" | sed 's/^|//;s/ //g')
            grep -Ev "${REGEX}" all-inactive.txt > tmp && mv tmp all-inactive.txt
          fi

          # Define outputs
          REPO_LIST=$(paste -sd "," all-inactive.txt)
          echo "inactive_count=$(wc -l < all-inactive.txt)" >> $GITHUB_OUTPUT
          echo "inactive_names=$REPO_LIST"           >> $GITHUB_OUTPUT

      - name: Show inactive repos
        run: |
          echo "Found ${{ steps.list.outputs.inactive_count }} inactive repos after exceptions:"
          echo "List of repos:"
          IFS=',' read -ra REPOS <<< "${{ steps.list.outputs.inactive_names }}"
          for repo in "${REPOS[@]}"; do
            echo "- $repo"
          done

      # Para ativar o arquivamento, descomente este passo:
      # - name: Archive each repo
      #   if: steps.list.outputs.inactive_count != '0'
      #   run: |
      #     while read repo; do
      #       echo "Archiving $repo..."
      #       gh api -X PATCH /repos/${{ github.repository_owner }}/$repo -f archived=true
      #     done < all-inactive.txt
